# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  sql.init.mode: always 
mybatis:
  mapper-locations: classpath:mapper/*.xml
