# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      
  # DevTools設定
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**,templates/**
    livereload:
      enabled: true
  
  # Thymeleafのキャッシュを無効化（開発時のみ）
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.example.demo.domain.user
  mapper-locations: 
    - classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
