# src/main/resources/application.yml
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      
  # DevTools設定
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**,templates/**
    livereload:
      enabled: true
  
  # Thymeleafのキャッシュを無効化（開発時のみ）
  thymeleaf:
    cache: false

  config:
    import: classpath:batch/config.yml

  web:
    resources:
      cache:
        # 開発中はキャッシュを完全に無効化する（有効期限を0にする）
        cachecontrol:
          max-age: 0 
          # no-cache, no-store, must-revalidate を設定
          no-cache: true
          no-store: true
          must-revalidate: true
      # リソースのバージョン管理を無効化（キャッシュさせない場合は不要）
      chain:
        cache: false
mybatis:
  type-aliases-package: com.example.demo.domain.user
  mapper-locations: 
    - classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
